In [2]:
# Meer Mustafa
# March 31, 2018


##### script that transforms csv's containing genomic signal features into 3D arrays (width x length x 1depth dimension per signal feature)

# 1 CSV = 1 signal
# each CSV is ordered by guides as rows and signal at genomic site as columns

# goal:
# is to produce from CSVs of signal vectors an output of np arrays 
# -- these arrays can be thought of as images - use the HW1 Question1.npz as an example
# save the arrays using np.savez('file') per x entry

import numpy as np

In [3]:
# 1. initialize a master array - a single array for each x input guide with shape (# of inputs, feature depth (# of signals), rows = 4 for a 4x repeated signal, columns = 200 for each bp signal)
# 2. read in csv iteratively (each csv contains one signal type for all x input guides) containing signal data
# 3. convert csv to np array
# 4. store each csv's elements (rows are signal at 1 guide) as the 1st dimension in np.array(shape=i, _, _)

# 5. after full input arrays is created and values are stored, 
# iterate through the first dimension (guides) of the full input array and save a single guide array in a new dir for inputs as np.savez('inputs/filename') named after the unique ID guide000001

# 6. after single arrays are saved as single files, create the master CSV that will be used to track the 1. guide file name and the 2. label for that guide file name


In [4]:
# iterate through the contents of a directory
from os import listdir
from os.path import isfile, join

# os.path gives both directories and files in path but want only files
onlyfiles = [f for f in listdir() if isfile(join( f))]

# with pattern match of files
onlyfiles = [f for f in listdir() if f.endswith('.R')]

# option 2 of pattern match
onlyfiles = [f for f in listdir() if '.R' in f]
onlyfiles


['processingBatchENCODEdownload.R',
 'createInputMatricesChipSeq_argsVersion.R',
 'createInputMatricesChipSeq.R',
 'Untitled.R',
 'BAMReadsOverBEDIntervals.R',
 'BAMReadsOverBEDIntervals_parallelBAMs.R']

In [91]:
# straight from csv to np array
from numpy import genfromtxt
import pandas as pd

# my_data = genfromtxt('../Data/CRISPRScreen/inputs/WDR5-human.A549.ENCFF851DKI.bam.MYC.bedgraph.200flanking_pileups.csv', delimiter=',')
# my_data

# option 2 for loading csv:
df=pd.read_csv('../Data/CRISPRScreen/inputs/chipvectorbedgraphCSVs/WDR5-human.A549.ENCFF851DKI.bam.MYC.bedgraph.200flanking_pileups.csv', sep=',',header=None)
print(df.dtypes)
print(df.values)
print(df.shape[0])

### replace incorrect format of the csv with nparray csv
# because the data is a literal string, we need to split based on whitespace
# then we can iterate through this resulting list of strings and turn them into integers
# index the df to pull out rows and columns
# option 1 - works
#[int(num) for num in df.iloc[0, ][0].split(' ')]
# option 2 - works
numlist = list(map(int, df.iloc[0,: ][0].split(' ')))
#np.array([numlist])
df.iloc[0,:][0] = np.array([numlist])
print(np.array(df.iloc[1,:][0] ))
type(df.iloc[1,:][0].split(' ') )

0    object
dtype: object
[[ '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3']
 [ '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 4 4 4 4']
 [ '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

list

In [92]:
df.shape

(112161, 1)

In [93]:
df.iloc[0,:][0]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
        2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3]])

In [168]:
## replace incorrect format of the csv with nparray csv
for i in range(0,df.shape[0]):
    # print(i)
    
    # save the ith row of the df back as a np array integer version of itself
    numlist = [int(num) for num in df.iloc[i , : ][0].split(' ')]
    
    # save back
    df.iloc[i, : ][0] = np.array([numlist])
    
    

In [172]:
type(df.iloc[0,:][0])

numpy.ndarray

In [176]:
df.iloc[0:20,:][0]

0     [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
1     [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
2     [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
3     [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
4     [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
5     [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
6     [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
7     [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
8     [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
9     [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
10    [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
11    [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,...
12    [[1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3,...
13    [[2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,...
14    [[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,...
15    [[3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,...
16    [[3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3,...
17    [[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3

In [34]:
masterInputsArray =  np.zeros(shape = (df.shape[0], # # of feature maps
                  42, # # of channels/feature depths e.g. RGB channels for images. this should be length of features (i.e. # of signal csv files)
                  1, # # of x rows
                  200) # # of y columns
        )
masterInputsArray

array([[[[ 0.,  0.,  0., ...,  0.,  0.,  0.]],

        [[ 0.,  0.,  0., ...,  0.,  0.,  0.]],

        [[ 0.,  0.,  0., ...,  0.,  0.,  0.]],

        ..., 
        [[ 0.,  0.,  0., ...,  0.,  0.,  0.]],

        [[ 0.,  0.,  0., ...,  0.,  0.,  0.]],

        [[ 0.,  0.,  0., ...,  0.,  0.,  0.]]],


       [[[ 0.,  0.,  0., ...,  0.,  0.,  0.]],

        [[ 0.,  0.,  0., ...,  0.,  0.,  0.]],

        [[ 0.,  0.,  0., ...,  0.,  0.,  0.]],

        ..., 
        [[ 0.,  0.,  0., ...,  0.,  0.,  0.]],

        [[ 0.,  0.,  0., ...,  0.,  0.,  0.]],

        [[ 0.,  0.,  0., ...,  0.,  0.,  0.]]],


       [[[ 0.,  0.,  0., ...,  0.,  0.,  0.]],

        [[ 0.,  0.,  0., ...,  0.,  0.,  0.]],

        [[ 0.,  0.,  0., ...,  0.,  0.,  0.]],

        ..., 
        [[ 0.,  0.,  0., ...,  0.,  0.,  0.]],

        [[ 0.,  0.,  0., ...,  0.,  0.,  0.]],

        [[ 0.,  0.,  0., ...,  0.,  0.,  0.]]],


       ..., 
       [[[ 0.,  0.,  0., ...,  0.,  0.,  0.]],

        [[ 0.,  0.,  0., ..

In [35]:
masterInputsArray.shape

(112161, 42, 1, 200)

In [178]:
# test out filling in the master array
masterInputsArray[0, # zeroth guide
                  0, # ith feature layer
                 :, # : results in repeated arrays, an index results in single occurence of array
                 :] = df.iloc[0,][0] # all the columns

In [179]:
masterInputsArray[0,
                  0,
                 :,
                 :]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.,  3.

In [180]:
masterInputsArray.shape

(112161, 42, 1, 200)

In [267]:
df.iloc[0,:][0].shape[1], len(csvfiles), csvfiles

(200,
 32,
 ['RCOR1-human.A549.ENCFF215VRH.bam.MYC.bedgraph.200flanking_pileups.csv',
  'CEBPB-human.A549.ENCFF000MWY.bam.MYC.bedgraph.200flanking_pileups.csv',
  'CTCF-human.A549.ENCFF000VPA.bam.MYC.bedgraph.200flanking_pileups.csv',
  'CHD1-human.A549.ENCFF019TJM.bam.MYC.bedgraph.200flanking_pileups.csv',
  'PHF8-human.A549.ENCFF156ZIB.bam.MYC.bedgraph.200flanking_pileups.csv',
  'KDM1A-human.A549.ENCFF843XEZ.bam.MYC.bedgraph.200flanking_pileups.csv',
  'MYC-human.A549.ENCFF518QII.bam.MYC.bedgraph.200flanking_pileups.csv',
  'MYC-human.A549.ENCFF000VOS.bam.MYC.bedgraph.200flanking_pileups.csv',
  'POLR2A-human.A549.ENCFF555WWS.bam.MYC.bedgraph.200flanking_pileups.csv',
  'POLR2A-human.A549.ENCFF000RME.bam.MYC.bedgraph.200flanking_pileups.csv',
  'CHD7-human.A549.ENCFF324ZFJ.bam.MYC.bedgraph.200flanking_pileups.csv',
  'CEBPB-human.A549.ENCFF940YYO.bam.MYC.bedgraph.200flanking_pileups.csv',
  'PBX3-human.A549.ENCFF000NEB.bam.MYC.bedgraph.200flanking_pileups.csv',
  'CHD4-human.A549.EN

In [201]:
masterInputsArray =  np.zeros(shape = (df.shape[0], # # of feature maps
                  len(csvfiles) , # # of channels/feature depths e.g. RGB channels for images. this should be length of features (i.e. # of signal csv files)
                  1, # # of x rows
                  df.iloc[0,:][0].shape[1] ) # pull the # of columns from the 1st csv signal file's columns i.e. # of y columns
        )
masterInputsArray.shape, df.shape

((112161, 15, 1, 200), (112161, 1))

In [94]:
masterInputsArray =  np.zeros(shape = (df.shape[0], # # of inputs
                  1 , # # of channels/feature depths e.g. RGB channels for images. this should be length of features (i.e. # of signal csv files)
                  1, # # of x rows
                  df.iloc[0,:][0].shape[1]) # pull the # of columns from the 1st csv signal file's columns i.e. # of y columns
        )

In [118]:
# 1-4. 
# store each csv's elements (rows are signal at 1 guide) as the 1st dimension in np.array(shape=i, _, _)

# iterate through csvs
filepattern = '.csv'
filedir = '../Data/CRISPRScreen/inputs/'
csvfiles = [f for f in listdir( filedir ) if f.endswith( filepattern )]




# make the master np array to hold all inputs (later save as single nps)
masterInputsArray =  np.zeros(shape = (df.shape[0], # # of feature maps
                  1 , # # of channels/feature depths e.g. RGB channels for images. this should be length of features (i.e. # of signal csv files)
                  1, # # of x rows
                  df.iloc[0,:][0].shape[1]) # pull the # of columns from the 1st csv signal file's columns i.e. # of y columns
        )
print('The shape of the master input is %s' %masterInputsArray.shape[0] )



# for featuresidx in range(0, masterInputsArray.shape[1]):
#     #print('Now working on loading in, correcting format to np array and saving to master input array:' %csvfiles[featuresidx])
    
#     # read in csv as pd df
#     #df = pd.read_csv('../Data/CRISPRScreen/inputs/chipvectorbedgraphCSVs/%s' %csvfiles[featuresidx], sep=',', header=None)
#     df = pd.read_csv('../Data/CRISPRScreen/inputs/chipvectorbedgraphCSVs/POLR2A-human.A549.ENCFF000RME.bam.MYC.bedgraph.200flanking_pileups.csv' , sep=',', header=None)
    
#     # convert df into integer np array
#     ## replace incorrect format of the csv with nparray csv
#     for i in range(0,df.shape[0]):
#         # print(i)

#         # save the ith row of the df back as a np array integer version of itself
#         numlist = [int(num) for num in df.iloc[i , : ][0].split(' ')]

#         # save back to original df
#         df.iloc[i, : ][0] = np.array([numlist])
        
        

#     # now data is in the correct format, need to save into a np array
#     # already are iterating through the feature depths (2nd dim), now
#     # iterate through the guides (1st dim)
#     for inputsidx in range(0, masterInputsArray.shape[0]):
#         masterInputsArray[inputsidx, # ith guide
#               featuresidx, # ith feature layer
#              :, # : results in repeated arrays, an index results in single occurence of array
#              :] 





####  all inputs, 1 feature test example




#for featuresidx in range(0, masterInputsArray.shape[1]):
#print('Now working on loading in, correcting format to np array and saving to master input array:' %csvfiles[featuresidx])

# read in csv as pd df
#df = pd.read_csv('../Data/CRISPRScreen/inputs/chipvectorbedgraphCSVs/%s' %csvfiles[featuresidx], sep=',', header=None)
df = pd.read_csv('../Data/CRISPRScreen/inputs/chipvectorbedgraphCSVs/POLR2A-human.A549.ENCFF000RME.bam.MYC.bedgraph.200flanking_pileups.csv' , sep=',', header=None)

# convert df into integer np array
## replace incorrect format of the csv with nparray csv
for i in range(0,df.shape[0]):
    # print(i)

    # save the ith row of the df back as a np array integer version of itself
    numlist = [int(num) for num in df.iloc[i , : ][0].split(' ')]

    # save back to original df
    df.iloc[i, : ][0] = np.array([numlist])



# now data is in the correct format, need to save into a np array
# already are iterating through the feature depths (2nd dim), now
# iterate through the guides (1st dim)
for inputsidx in range(0, masterInputsArray.shape[0]):
    masterInputsArray[inputsidx, # ith guide
          0, # ith feature layer
         :, # : results in repeated arrays, an index results in single occurence of array
         :] = df.iloc[inputsidx, : ]

    

The shape of the master input is 112161


ValueError: setting an array element with a sequence.

In [121]:
masterInputsArray.sum(), df.shape,  df.iloc[0,:] 

(0.0, (112161, 1), 0    [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,...
 Name: 0, dtype: object)

In [124]:
df

filedirToSaveTo = '../Data/CRISPRScreen/inputs/chip_npz/'
filedirToPullFrom = '/Data/CRISPRScreen/inputs/chip_npz/'
featureName = '.ChIP'

filePathAndNameListToSaveTo = list()
filePathAndNameListToPullFrom = list()
filePathAndNameListToSaveToDNA = list()

# create unique IDs for guides
guideIDNames = list()
for i in range(1, df.shape[0]+1): # ranges from 1 to the max number of inputs
    #print(i)
    guideIDNames.append( 'MYCScreen_%06d' %i) # pad zeroes and use string substitution
    
    # save the np array using np.savez, automatically gives the array, that is saved inside the npz, the name 'arr_0'
    
    # first create the name the file will be named after
    # automatically has .npz extension name
    filePathAndNameToSaveTo = str( guideIDNames[len(guideIDNames)-1] + '_chip' + '.npy')
    filePathAndNameListToSaveTo.append(filePathAndNameToSaveTo)
    
    filePathAndNameToSaveToDNA = str( guideIDNames[len(guideIDNames)-1] + '_DNA' + '.npy')
    filePathAndNameListToSaveToDNA.append(filePathAndNameToSaveToDNA)
    
    #str(filedirToSaveTo + guideIDNames[len(guideIDNames)-1] + featureName)
    
    
    # create separate name to pull from
    filePathAndNameToPullFrom = str(filedirToPullFrom + guideIDNames[len(guideIDNames)-1] + '_chip' + featureName)
    # create list of file path&names
    filePathAndNameList.append(filePathAndNameToPullFrom)
    
    # save the ith input, including all features
    # TO TROUBLESHOOT SAVE THE ITH INPUT AND ONLY 1 FEATURE TYPE
    #np.save(filePathAndNameToSaveTo, df[i,:] )
    np.savez(str(filedirToSaveTo + guideIDNames[len(guideIDNames)-1] + '_chip'), x = df.iloc[i,:][0] )

    
    

# check the names
guideIDNames[0:3],guideIDNames[-5:]

IndexError: single positional indexer is out-of-bounds

In [51]:
# now that creating the master np array is done, let's segment the full array into singlular inputs. 
# this will make it much easier later on because of memory usage from loading in large amounts of data

filedirToSaveTo = '../Data/CRISPRScreen/inputs/chip_npz/'
filedirToPullFrom = '/Data/CRISPRScreen/inputs/chip_npz/'
featureName = '.ChIP'

filePathAndNameListToSaveTo = list()
filePathAndNameListToPullFrom = list()
filePathAndNameListToSaveToDNA = list()

# create unique IDs for guides
guideIDNames = list()
for i in range(1, masterInputsArray.shape[0]+1): # ranges from 1 to the max number of inputs
    #print(i)
    guideIDNames.append( 'MYCScreen_%06d' %i) # pad zeroes and use string substitution
    
    # save the np array using np.savez, automatically gives the array, that is saved inside the npz, the name 'arr_0'
    
    # first create the name the file will be named after
    # automatically has .npz extension name
    filePathAndNameToSaveTo = str( guideIDNames[len(guideIDNames)-1] + '_chip' + '.npy')
    filePathAndNameListToSaveTo.append(filePathAndNameToSaveTo)
    
    filePathAndNameToSaveToDNA = str( guideIDNames[len(guideIDNames)-1] + '_DNA' + '.npy')
    filePathAndNameListToSaveToDNA.append(filePathAndNameToSaveToDNA)
    
    #str(filedirToSaveTo + guideIDNames[len(guideIDNames)-1] + featureName)
    
    
    # create separate name to pull from
    filePathAndNameToPullFrom = str(filedirToPullFrom + guideIDNames[len(guideIDNames)-1] + '_chip' + featureName)
    # create list of file path&names
    filePathAndNameList.append(filePathAndNameToPullFrom)
    
    # save the ith input, including all features
    # TO TROUBLESHOOT SAVE THE ITH INPUT AND ONLY 1 FEATURE TYPE
    #np.save(filePathAndNameToSaveTo, masterInputsArray[i,:,:,:] )

    
    

# check the names
guideIDNames[0:3],guideIDNames[-5:]

# now have a list of names to name individual file names after (1 file per input)
# iterate through the inputs in the master array, subset the master, and save in npz file

# for np.savez:
# If arguments are passed in with no keywords, the corresponding variable names, in the .npz file, are ‘arr_0’, ‘arr_1’, etc. 
# If keyword arguments are given, the corresponding variable names, in the .npz file will match the keyword names.

# e.g.:
# npzfile = np.load('Question1.npz') # 'Question1.npz' is provided under /beegfs/ga4493/data/HW2 folder at HPC
# print(npzfile.files) # check the variable names
# x = npzfile['x']
# w = npzfile['w']
# b = npzfile['b']



(['MYCScreen_000001', 'MYCScreen_000002', 'MYCScreen_000003'],
 ['MYCScreen_112157',
  'MYCScreen_112158',
  'MYCScreen_112159',
  'MYCScreen_112160',
  'MYCScreen_112161'])

In [60]:
filePathAndNameListToSaveTo[0], masterInputsArray[1,:,:,:], masterInputsArray[1,:,:,:].shape

('MYCScreen_000001_chip.npy', array([[[ 0.,  0.,  0., ...,  0.,  0.,  0.]],
 
        [[ 0.,  0.,  0., ...,  0.,  0.,  0.]],
 
        [[ 0.,  0.,  0., ...,  0.,  0.,  0.]],
 
        ..., 
        [[ 0.,  0.,  0., ...,  0.,  0.,  0.]],
 
        [[ 0.,  0.,  0., ...,  0.,  0.,  0.]],
 
        [[ 0.,  0.,  0., ...,  0.,  0.,  0.]]]), (42, 1, 200))

In [64]:
np.savez(filePathAndNameListToSaveTo[0], masterInputsArray[1,:,:,:] )

In [68]:
a = np.load(filePathAndNameListToSaveTo[0]+'.npz')
a.files
a['arr_0']

array([[[ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       ..., 
       [[ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  0.,  0.,  0.]]])

NameError: name 'csvfiles' is not defined

In [75]:
d={ 'x':masterInputsArray[1,1,:,:] , 'y':masterInputsArray[1,2,:,:]}
print(d)


np.savez('test', **d )

# loading in the npz singular files - put this code inside the dataloader class object
npzfile = np.load('test.npz')

print(npzfile.files)
testarray = npzfile['x']
testarray


{'x': array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.

In [76]:
# iterate through csvs
filepattern = '.csv'
filedir = '../Data/CRISPRScreen/inputs/chipvectorbedgraphCSVs/'
csvfiles = [f for f in listdir( filedir ) if f.endswith( filepattern )]
csvfiles

['RCOR1-human.A549.ENCFF215VRH.bam.MYC.bedgraph.200flanking_pileups.csv',
 'CEBPB-human.A549.ENCFF000MWY.bam.MYC.bedgraph.200flanking_pileups.csv',
 'CTCF-human.A549.ENCFF000VPA.bam.MYC.bedgraph.200flanking_pileups.csv',
 'CHD1-human.A549.ENCFF019TJM.bam.MYC.bedgraph.200flanking_pileups.csv',
 'PHF8-human.A549.ENCFF156ZIB.bam.MYC.bedgraph.200flanking_pileups.csv',
 'KDM1A-human.A549.ENCFF843XEZ.bam.MYC.bedgraph.200flanking_pileups.csv',
 'MYC-human.A549.ENCFF518QII.bam.MYC.bedgraph.200flanking_pileups.csv',
 'MYC-human.A549.ENCFF000VOS.bam.MYC.bedgraph.200flanking_pileups.csv',
 'POLR2A-human.A549.ENCFF555WWS.bam.MYC.bedgraph.200flanking_pileups.csv',
 'POLR2A-human.A549.ENCFF000RME.bam.MYC.bedgraph.200flanking_pileups.csv',
 'CHD7-human.A549.ENCFF324ZFJ.bam.MYC.bedgraph.200flanking_pileups.csv',
 'CEBPB-human.A549.ENCFF940YYO.bam.MYC.bedgraph.200flanking_pileups.csv',
 'PBX3-human.A549.ENCFF000NEB.bam.MYC.bedgraph.200flanking_pileups.csv',
 'CHD4-human.A549.ENCFF449GDV.bam.MYC.bedgrap

In [ ]:
filePathAndNameList

In [260]:
filedir = '../Data/CRISPRScreen/inputs/'

In [261]:
filePathAndName = str(filedir + guideIDNames[0] + featureName)
filePathAndName

'../Data/CRISPRScreen/inputs/MYCScreen_000001.ChIP'

In [250]:
np.savez(filename, masterInputsArray[0,:,:,:] )

In [254]:
# loading in the npz singular files - put this code inside the dataloader class object
npzfile = np.load('MYCScreen_000001.ChIP.npz')
print(npzfile.files)
testarray = npzfile['arr_0']
testarray

['arr_0']


array([[[ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       ..., 
       [[ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  0.,  0.,  0.]]])

In [54]:
### master CSV creation
lib = pd.read_csv('../Data/CRISPRScreen/A549Rep1MYCScreen_OverreppedGuideRemoved_NormalizedReadCounts_FunctionalLabelAgainstTop1PercentNT2018-03-31.csv')
print(lib.columns)
#lib.loc[:,['functionalLabeltop1percentNT']].tolist()
labelslist = lib['functionalLabeltop1percentNT'].tolist()
cslist = lib['bc8VSbc1'].tolist()
len(labelslist)
subsetlabelslist,subsetCSlist = labelslist[0 : masterInputsArray.shape[0]], cslist[0 : masterInputsArray.shape[0]]


d = {'InputUniqueID' : guideIDNames, 
     'label' : subsetlabelslist,
     'CS' : subsetCSlist,
      'ChIPFileSource' : filePathAndNameListToSaveTo,
     'DNAFileSource' : filePathAndNameListToSaveToDNA
    }
masterCSV = pd.DataFrame(data=d)
masterCSV.head



Index(['UniqueID', 'chr', 'sgRNA_start', 'sgRNA_end', 'strand',
       'sgRNA_sequence', 'Set', 'Gene', 'bc1', 'bc2', 'bc3', 'bc4', 'bc5',
       'bc6', 'bc7', 'bc8', 'MYCLibrary01', 'finalToInitial', 'bc1VSbc1',
       'bc2VSbc1', 'bc3VSbc1', 'bc4VSbc1', 'bc5VSbc1', 'bc6VSbc1', 'bc7VSbc1',
       'bc8VSbc1', 'functionalLabeltop1percentNT'],
      dtype='object')


/Users/meer/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


<bound method NDFrame.head of               CS             ChIPFileSource             DNAFileSource  \
0      -0.083997  MYCScreen_000001_chip.npy  MYCScreen_000001_DNA.npy   
1       0.916003  MYCScreen_000002_chip.npy  MYCScreen_000002_DNA.npy   
2      -0.557929  MYCScreen_000003_chip.npy  MYCScreen_000003_DNA.npy   
3      -1.907120  MYCScreen_000004_chip.npy  MYCScreen_000004_DNA.npy   
4       0.746078  MYCScreen_000005_chip.npy  MYCScreen_000005_DNA.npy   
5       0.303026  MYCScreen_000006_chip.npy  MYCScreen_000006_DNA.npy   
6      -0.668960  MYCScreen_000007_chip.npy  MYCScreen_000007_DNA.npy   
7       0.205509  MYCScreen_000008_chip.npy  MYCScreen_000008_DNA.npy   
8      -0.244462  MYCScreen_000009_chip.npy  MYCScreen_000009_DNA.npy   
9      -1.083997  MYCScreen_000010_chip.npy  MYCScreen_000010_DNA.npy   
10     -0.614512  MYCScreen_000011_chip.npy  MYCScreen_000011_DNA.npy   
11      0.626496  MYCScreen_000012_chip.npy  MYCScreen_000012_DNA.npy   
12      1.003465  MYC

In [55]:
# write out csv
masterCSV.to_csv("../Data/CRISPRScreen/masterDataLoadingCSV.csv")

In [46]:
len(subsetCSlist)

112161

In [ ]:
# write out csv
df.to_csv(""C:/Folder/UpdatedData.csv")

In [314]:
len(np.random.randint(low = 0, high = 1, size = masterInputsArray.shape[0]))

112161

In [308]:
np.random.randint(low = 0, high = 1, size = masterInputsArray.shape[0])

array([0, 0, 0, ..., 0, 0, 0])

In [292]:
filePathAndNameCSV = pd.DataFrame(data = guideIDNames, index = np.arange(masterInputsArray.shape[0]) , columns=['InputUniqueID'])
filePathAndNameCSV.head

ValueError: Shape of passed values is (1, 30507), indices imply (1, 112161)

In [ ]:
# write out csv
df.to_csv(""C:/Folder/UpdatedData.csv")

In [7]:
# creating an np array with 3 dimensions:
x = np.array([1,2,3])
#x_zeropad = np.zeros([x.shape[0],x.shape[1]+2,x.shape[2]+2])
#x_zeropad[:,1:-1,1:-1] = x
x

AttributeError: module 'numpy' has no attribute 'tensor'

In [ ]:
### create a class specific for our data
from torch.utils.data import Dataset, DataLoader
import pandas as pd
import os
from skimage import io
import torch
from skimage import color

class ChestXrayDataset(Dataset):
    """Chest X-ray dataset from https://nihcc.app.box.com/v/ChestXray-NIHCC."""

    def __init__(self, csv_file, root_dir, transform=None):
        """
        Args:
            csv_file (string): Path to the csv file filename information.
            root_dir (string): Directory with all the images.
            transform (callable, optional): Optional transform to be applied
                on a sample.
        """
        self.data_frame = pd.read_csv(csv_file)
        self.root_dir = root_dir
        self.transform = transform

    def __len__(self):
        return len(self.data_frame)

    def __getitem__(self, idx):
        img_name = os.path.join(self.root_dir,
                                self.data_frame.iloc[idx, 0])
        
        #some cases io.imread brings more channels than 1 due to bitsize issues
        image = io.imread(img_name,as_grey=True)
        #or we can use the following
        #if len(image.shape) > 2 and image.shape[2] == 4:
        #    image = image[:,:,0]
        
        # data transfrom to zero mean unit variance
        image = (image - image.mean()) / image.std()
            
        image_class = self.data_frame.iloc[idx, -1]
        #print(img_name,image.shape)

        sample = {'x': image[None,:], 'y': image_class}

        if self.transform:
            sample = self.transform(sample)

        return sample

In [ ]:

### creating data loader objects

import matplotlib.pyplot as plt
import numpy as np
from torch.autograd import Variable 
import time
import copy


BATCH_SIZE = 16
## data loaders
chestXray_TrainData = ChestXrayDataset(csv_file='HW2_RandomTrainSet.csv',
                                    root_dir='images')
train_loader = DataLoader(chestXray_TrainData, batch_size=BATCH_SIZE,
                        shuffle=True, num_workers=4)


chestXray_ValidationData = ChestXrayDataset(csv_file='HW2_RandomValidationSet.csv',
                                    root_dir='images')
validation_loader = DataLoader(chestXray_ValidationData, batch_size=BATCH_SIZE,
                        shuffle=True, num_workers=4)


use_gpu = torch.cuda.is_available()


dataset_sizes = {'train': len(chestXray_TrainData), 'val': len(chestXray_ValidationData)}